config/routes.rb
Paymeback::Application.routes.draw do

  get "users/show"
  resources :nachrichtens
  resources :debits
  resources :friends

 get "startsite/demo" 
  

  ActiveAdmin.routes(self)

  devise_for :users, :path => 'accounts'

  resources :users 
  root to: 'startsite#startsite'

end

app/models/friend.rb
class Friend < ActiveRecord::Base
  attr_accessible :friend_id, :user_id, :user, :friend, :accepted
  belongs_to :user,:foreign_key => "user_id"
  belongs_to :user, :foreign_key => "friend_id"
  belongs_to :friendship, :class_name => "User"
  validates_presence_of :friend_id, :user_id
  validates :friend_id, :uniqueness => {:scope => :user_id}
  validate :check_friend_id_and_user_id
end

def check_friend_id_and_user_id
	errors.add(:friend_id, "Man kann sich nicht selber als Freund hinzufuegen") if user_id==friend_id
end

app/controllers/friends_controller.rb
class FriendsController < ApplicationController
 #autocomplete :debit, :emailcurrentuser
  # GET /friends
  # GET /friends.json
  #def index
  #  @friends = Friend.all

  #  respond_to do |format|
  #    format.html # index.html.erb
  #    format.json { render json: @friends }
  #  end
  #end

  # GET /friends/1
  # GET /friends/1.json
  def show
    #@friend = Friend.find(params[:id])

   #respond_to do |format|
    #  format.html # show.html.erb
     # format.json { render json: @friend }
    #end
  end
  # GET /friends/1/edit
  #def edit
  #  @friend = Friend.find(params[:id])
  #end

  # POST /friends
  # POST /friends.json
  def create    
    #eventuell implementieren und zu verhindern, dass ein bereits hinzugefügter nutzer noch ein mal hinzugefügt wird.
    #
    #@exists = Friend.where('user_id like ? AND friend_id like ?', "%#{current_user.id}%", "%#{:friend_id}%" ).first
    #if @exists.user_id == current_user.id
    #    flash[:error] = "Hinzufuegen nicht moeglich."
    #    redirect_to friends_path
    #else
    #  @friend = current_user.friends.build(:friend_id => params[:friend_id])
    #  if @friend.save
    #    flash[:notice] = "Freund hinzugefuegt."
    #    redirect_to friends_path
    #  end
    #end
    #
    #
    #user = User.where('id like ?', "%#{:friend_id}%")
    @friend = current_user.friends.build(:friend_id => params[:friend_id], :user_id => params[:friend_id])
       if @friend.save
        flash[:notice] = "Freund hinzugefuegt."
        redirect_to friends_path
      else
        flash[:error] = "Hinzufuegen nicht moeglich."
        redirect_to friends_path
      end    
  end
  # Freundschaftsanfrage annehmen
  def update
    @friend = Friend.find(params[:id])
    respond_to do |format|
        @friend.accepted = true
        @friend.save
        format.html { redirect_to friends_path, notice: 'Anfrage erfolgreich angenommen.' }
        format.json { head :no_content }
    end
  end
  # Freundschaftsanfrage ablehnen
  def ablehnen
    @friend = current_user.friends.find(params[:id])
    @friend.destroy
    #@friend = Friend.find(:first, params[:id])
    #Friend.where('id like ? ', "%#{:id}%")
    #@friend.destroy
    flash[:notice] = "Anfrage abgelehnt."
    redirect_to friends_path
  end
  def destroy
    @friend = Friend.find(params[:id])
    @friend.destroy
    flash[:notice] = "Freundschaft beendet."
    redirect_to friends_path    
  end
end

app/helpers/friends_helper.rb
module FriendsHelper
end

app/views/friends/_form.html.erb
<%= form_for (@friend, :html => { :class => 'form-horizontal' } do |f| %>
  <% if @friend.errors.any? %>
    <div id="error_explanation">
      <h2>Eintrag konnte nicht erstellt werden! <%= @friend.errors.count %> Fehler wurden gefunden </h2>

      <ul>
      <% @friend.errors.full_messages.each do |msg| %>
      
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  
  <div class="control-group">
    <%= f.label :user_id, :class => 'control-label' %>
    <div class="controls">
      <%= f.number_field :user_id, :class => 'number_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :friend_id, :class => 'control-label' %>
    <div class="controls">
      <%= f.number_field :friend_id, :class => 'number_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :accepted, :class => 'control-label' %>
    <div class="controls">
      <%= f.check_box :accepted, :class => 'check_box' %>
    </div>
  </div>

  <div class="form-actions">
    <%= f.submit nil, :class => 'btn btn-primary' %>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                friends_path, :class => 'btn' %>
  </div>
<% end %>

app/views/friends/edit.html.erb
<%- model_class = Friend -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human %></h1>
</div>
<%= render :partial => 'form' %>

app/views/friends/index.html.erb
<%- model_class = Friend -%>


    <div class="container">
    <% flash.each do |name, msg| %>
      <div class="alert alert-<%= name == :notice ? "success" : "error" %>">
      <a class="close" data-dismiss="alert">x</a>
      <%= msg  %>
      </div>
    <% end %>
  </div>



<div class="well sidebar-nav">
<div class="page-header">
  <h1><%=t '.Deine Freunde' %></h1>
</div>
<table class="table table-striped">  
  
    <tr>  
  <th><%= model_class.human_attribute_name(:Person) %></th>
  </tr>  
  <% for friend in current_user.friends%>
  <%if friend.accepted == true%>  

  <% freund = User.where(id: friend.friend_id).first%>


      <tbody>
      <td><%=h freund.firstname%> <%=freund.lastname%></td>
      <%if freund.photo_file_size.blank? %>
      <td><img src="/assets/missing_small.png"   /> </td>
      <%else%>
      <td><%= image_tag freund.photo.url(:tiny)  %> </td>
      <%end%>
      <td><%= link_to " Profil anzeigen", user_path(:id => freund), :method => :get , :class => 'btn icon-user', :id => "profilanzeigen"%>

        <%= link_to " Nachricht senden", new_nachrichten_path(:sentto => freund), :method => :get, :class =>'btn icon-envelope', :id => "nachrichtsenden"%>
      <%= link_to " Freundschaft beenden", friend, :method => :delete , :class => 'btn btn-danger icon-remove', :id => "freundschaftbeenden"%>  </td></tr>

   <%end%>
   <%end%>
    
   
  <!-- inverse suche-->
   <% for friend in current_user.inverse_friends%>
  <%if friend.accepted == true%>  
  <% freund = User.where(id: friend.user_id).first%>
 
 
     
      <td><%=h freund.firstname%> <%= freund.lastname%></td>
       <%if freund.photo_file_name.blank? %>
      <td><img src="/assets/missing_small.png"   /> </td>
      <%else%>
      <td><%= image_tag freund.photo.url(:tiny)  %> </td>
      <%end%>
      <td><%= link_to " Profil anzeigen", user_path(:id => freund), :method => :get , :class => 'btn icon-user'%>
        <%= link_to " Nachricht senden", new_nachrichten_path(:sentto => freund), :method => :get, :class =>'btn icon-envelope'%>
      <%= link_to " Freundschaft beenden", friend, :method => :delete , :class => 'btn btn-danger icon-remove', :id => "freundschaftbeenden"%> </td>
   <%end%>
  </tr>
  <%end%>
  </tbody>
  
</table>
</div>
<!-- Freundschaftsanfragen-->
<div class="well sidebar-nav"><div class="page-header">
  <h1><%=t '.Freundschaftsanfragen' %></h1>
</div>
<table class="table table-striped">      
      <tr>
      <th><%= model_class.human_attribute_name(:Person) %></th>
      
  <% typ = Friend.where(friend_id: current_user.id)%>
  <%typ.all.each do |type|%>
  <%if type.accepted == false%> 
      <% user = User.where(id:  type.user_id).first%>

      <tbody>
    <td>  <%= user.firstname %> <%=user.lastname%></td>
     <%if freund.photo_file_name.blank? %>
      <td><img src="/assets/missing_small.png"   /> </td>
      <%else%>
      <td><%= image_tag freund.photo.url(:tiny)  %> </td>
      <%end%>
    <td> <%= link_to " Profil anzeigen", user_path(:id => user), :method => :get , :class => 'btn icon-user '%>
      <%= link_to " Nachricht senden", new_nachrichten_path(:sentto => type), :method => :get, :class =>'btn icon-envelope'%>
    <%= link_to " annehmen", type, :method => :put, :class => 'btn btn-success icon-ok', :id => "freundannehmen" %> 
    <%= link_to " ablehnen", type, :method => :delete, :class => 'btn btn-danger'%></td>
      <%end%>
      </tbody>
    <%end%>

</table>
</div>
<!-- Ausstehende Freundschaftsanfragen-->
<div class="well sidebar-nav">
<div class="page-header">
  <h1><%=t '.Ausstehende Freundschaftsanfragen' %></h1>
</div>
<table class="table table-striped">
  <tr>   
  <th><%= model_class.human_attribute_name(:Person) %></th>
      </thead>
      <% for friend in current_user.friends%>
      <%if friend.accepted == false%>  
      <% freund = User.where(id: friend.friend_id).first%>
      <tbody>
      <td><%= freund.firstname%> <%= freund.lastname%> </td>
       <%if freund.photo_file_name.blank? %>
      <td><img src="/assets/missing_small.png"   /> </td>
      <%else%>
      <td><%= image_tag freund.photo.url(:tiny)  %> </td>
      <%end%>
       <td> <%= link_to " Profil anzeigen", user_path(:id => freund), :method => :get, :class => 'btn icon-user' %>
        <%= link_to " Nachricht senden", new_nachrichten_path(:sentto => freund), :method => :get, :class =>'btn icon-envelope'%>
        <%= link_to " Anfrage stornieren", friend, :method => :delete , :class => 'btn btn-danger icon-remove'%></td>
  <%end%>
  <% end %>
</tr>
 </tbody>
 </table>
</div>

   <p><%= link_to " Freunde finden", new_friend_path , :class => 'btn btn-success icon-user',:id => "freundefinden" %></p>

app/views/friends/new.html.erb
<%- model_class = Friend -%>
<div class="well sidebar-nav">
<div class="page-header">
  <h1><%=t '.Freunde hinzufügen', :model => model_class.model_name.human %></h1>
</div>
<table class="table table-striped">
  <% if current_user %>
    <thead> 
      <tr>
      <th><%= model_class.human_attribute_name(:Vorname) %></th>
      <th><%= model_class.human_attribute_name(:Nachname) %></th>
      </thead>
      <!-- hier muss not like hin-->
    <% user = User.find(:all)%>
   
    <tbody>

    <% user.each do |benutzer| %>
      <%if Friend.where(user_id: current_user.id, friend_id: benutzer.id).exists?%>
      <%elsif Friend.where(friend_id: current_user.id, user_id: benutzer.id).exists?%> 

      <%else%>
      <%if current_user.email == benutzer.email%>
      
      <%else%>
      <td><%= benutzer.firstname %></td>
      <td><%= benutzer.lastname %></td>
      <%if benutzer.photo_file_name.blank? %>
        <td><img src="/assets/missing_small.png"   /> </td>
      <%else%>
        <td><%= image_tag benutzer.photo.url(:tiny)  %> </td>
      <%end%>
      <td><%= link_to " Profil anzeigen", user_path(:id => benutzer), :method => :get, :class => 'btn icon-user', :id => "profilanzeigen"%>
            <%= link_to "Als Freund hinzufügen",  friends_path(:friend_id => benutzer), :method => :post, :class => 'btn btn-success icon-plus-sign', :id => "freundehinzufuegen"%></td>
      <%end%>

  </tbody>
      </tr>
      <%end%>
    <%end%>
  <%end%>
</table>
<p><%= link_to " Zurück", friends_path , :class => 'btn icon-arrow-left' %></p>
</div>

app/views/friends/show.html.erb
<%- model_class = Friend -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:user_id) %>:</strong></dt>
  <dd><%= @friend.user_id %></dd>
  <dt><strong><%= model_class.human_attribute_name(:friend_id) %>:</strong></dt>
  <dd><%= @friend.friend_id %></dd>
  <dt><strong><%= model_class.human_attribute_name(:accepted) %>:</strong></dt>
  <dd><%= @friend.accepted %></dd>
</dl>

<div class="form-actions">
  <%= link_to t('.back', :default => t("helpers.links.back")),
              friends_path, :class => 'btn'  %>
  <%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_friend_path(@friend), :class => 'btn' %>
  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              friend_path(@friend),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>
</div>