config/routes.rb
Paymeback::Application.routes.draw do

  get "users/show"
  resources :nachrichtens
  resources :debits
  resources :friends

 get "startsite/demo" 
  

  ActiveAdmin.routes(self)

  devise_for :users, :path => 'accounts'

  resources :users 
  root to: 'startsite#startsite'

end

app/models/nachrichten.rb
class Nachrichten < ActiveRecord::Base
  attr_accessible :body, :sentby, :sentto, :topic, :read
  belongs_to :user
  belongs_to :nachricht, :class_name => "User"
  # Prüfung auf Vorhandensein 
  validates_presence_of :sentby, :sentto, :topic, :body
end

app/controllers/nachrichtens_controller.rb
class NachrichtensController < ApplicationController
  # GET /nachrichtens
  # GET /nachrichtens.json
  def index
    @nachrichtens = Nachrichten.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @nachrichtens }
    end
  end

  # GET /nachrichtens/1
  # GET /nachrichtens/1.json
  def show
    @nachrichten = Nachrichten.where(sentby: current_user.id, id: params[:id]).first
    if @nachrichten ==nil
      @nachrichten = Nachrichten.where(sentto: current_user.id, id: params[:id]).first
      if @nachrichten==nil
        flash[:error] ="Zugriff verweigert."
        redirect_to root_url
      end 
    end
    if @nachrichten ==nil
    else
    if @nachrichten.read == false
      if @nachrichten.sentto == current_user.id       
      @nachrichten.read = true
      respond_to do |format|
      if @nachrichten.update_attributes(params[:read => true])
        format.html # show.html.erb
        format.json { render json: @nachrichten }
      else
        flash[:error] ="Ein Fehler ist aufgetreten."
        redirect_to root_url
      end
    end
    end
    else
      respond_to do |format|
        format.html # show.html.erb
        format.json { render json: @nachrichten }
      end
    end
  end
  end
  # GET /nachrichtens/new
  # GET /nachrichtens/new.json
  def new
    @nachrichten = Nachrichten.new
    @sentto = params[:sentto]
    @topic = params[:topic]
    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @nachrichten }
    end
  end
  # GET /nachrichtens/1/edit
  def edit
    @nachrichten = Nachrichten.find(params[:id])
    @sentto = @nachrichten.sentby
    @topic = "re:"+@nachrichten.topic
    @nachrichtens = Nachrichten.new
        redirect_to new_nachrichten_path(:sentto => @sentto, :topic => @topic), :method => :get
  end

  # POST /nachrichtens
  # POST /nachrichtens.json
  def create
    @nachricht = Nachrichten.new(params[:nachrichten])
    #(:sentby => params[:sentby],:sentto =>params[:sentto],:topic => params[:topic],:body =>params[:body])
    #respond_to do |format|
      if @nachricht.save
        flash[:notice] ="Nachricht verschickt."
        redirect_to root_url
      else
        flash[:error] ="Nachricht konnte nicht verschickt werden."
        redirect_to root_url
      end
    #end
    
  end

  def answer
    @nachrichten = Nachrichten.find(params[:id])
    @sentto = @nachrichten.sentby
    @sentby = @nachrichten.sentto
    @topic = "re:"+@nachrichten.topic
    @nachrichtens = Nachrichten.new(params[:sentto => :@sentto], params[:sentby => :@sentto], params[:topic => :@topic])
    
    if @nachricht.save
        flash[:notice] ="Antwort verschickt."
        redirect_to root_url
      else
        flash[:error] ="Antwort konnte nicht verschickt werden."
        redirect_to root_url
      end
  end

  # PUT /nachrichtens/1
  # PUT /nachrichtens/1.json
  def update
    @nachrichten = Nachrichten.find(params[:id])
    respond_to do |format|
        @nachrichten.read = true
        @nachrichten.save
        format.html { redirect_to nachrichten, notice: 'Nachrichten was successfully updated.' }
        format.json { head :no_content }
      end
  end


  # DELETE /nachrichtens/1
  # DELETE /nachrichtens/1.json
  def destroy
    @nachrichten = Nachrichten.find(params[:id])
    @nachrichten.destroy

    respond_to do |format|
      format.html { redirect_to nachrichtens_url }
      format.json { head :no_content }
    end
  end
end

app/views/nachrichtens/_form.html.erb
<%= form_for @nachrichten, :html => { :class => 'form-horizontal' } do |f| %>
   <% if @nachrichten.errors.any? %>
    <div id="error_explanation">
      <h2>Eintrag konnte nicht erstellt werden! <%= @nachrichten.errors.count %> Fehler wurden gefunden </h2>

      <ul>
      <% @nachrichten.errors.full_messages.each do |msg| %>
      
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  
   <div class="control-group">
    <div class="field">
      <%if current_user%>
      <%= f.hidden_field :sentby, :value=> current_user.id %><br>
      <%else%>
      <% dummy = User.where(email: "dummy@paymeback.de").first%>
      <%= f.hidden_field :sentby, :value=>dummy.id  %><br>
      <%end%>
  </div>
</div>

  <% user = User.where(id: @sentto).first%>  
  <div class="control-group">
    <%= f.label :Empfänger, :class => 'control-label' %>
    <%if current_user%>    
    <%= f.label :title, user.firstname + " " + user.lastname , :class => 'control-label' %>
    <%else%>
      <%= f.label :title, "Administrator" , :class => 'control-label' %>
      <%end%>
    <div class="field">
    <%= f.hidden_field :sentto, :value=> @sentto %><br>
  </div>
  </div>

  <div class="control-group">
    <%= f.label :Betreff, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :topic,:value=> @topic , :class => 'text_area', :id=>'topic' %>
    </div>
  </div>
  
  <div class="control-group">
    <%= f.label :Nachricht, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_area :body,  :size => "50x10", :class => 'text_area', :id=>'body' %>
    </div>
  </div>  

  <div class="form-actions">
    <%= f.submit 'Senden', :class => 'btn btn-success', :id =>'senden'%>
    <%= link_to t('.Zurück'),
                nachrichtens_path, :class => 'btn ' %>
  </div>
<% end %>

app/views/nachrichtens/edit.html.erb
<%- model_class = Nachrichten -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human %></h1>
</div>
<%= render :partial => 'form' %>

app/views/nachrichtens/index.html.erb
<%- model_class = Nachrichten -%> 


    <div class="container">
    <% flash.each do |name, msg| %>
      <div class="alert alert-<%= name == :notice ? "success" : "error" %>">
      <a class="close" data-dismiss="alert">x</a>
      <%= msg  %>
      </div>
    <% end %>
  </div>

    <div class="well sidebar-nav">
      <% news1 = Nachrichten.where(sentto: current_user.id)%>
      <% news = news1.reverse%>
      <% if news.blank?%>
        <h1>Bisher haben Sie keine Nachrichten empfangen</h1>

      <%else%>
      <div class="page-header">
        <h1><%=t '.Empfangene Nachrichten' %></h1>
      </div>
      <table class="table table-striped">
        <thead>
          <tr>
            <th><%= model_class.human_attribute_name(:Von )%></th>
            <th><%= model_class.human_attribute_name(:Betreff) %></th>
            <th><%= model_class.human_attribute_name(:Gelesen) %></th>
            <th><%= model_class.human_attribute_name(:Gesendet_am) %></th>
            <th><%= model_class.human_attribute_name(:um) %></th>
            <!--<th><%=t '.actions', :default => t("helpers.actions") %></th>-->
          </tr>
        </thead>
        <tbody>
          <% news.each do |nachrichten| %>
            <tr>
              <td><%user1 = User.where(id: nachrichten.sentby).first%><%=user1.firstname%></td>
              <td><%= nachrichten.topic %></td>
              <%if nachrichten.read==false%>
                <td>nein</td>
              <%else%>
                <td>ja</td>
              <%end%>
              <td><%= nachrichten.created_at.day%>.<%=nachrichten.created_at.month%>.<%= nachrichten.created_at.year%></td>
              <td><%= nachrichten.created_at.hour%>:<%= nachrichten.created_at.min%></td>
              <td>
                <%= link_to 'anzeigen', nachrichten_path(:id => nachrichten), :class => 'btn ', :id => "ansehen" %>
                <%= link_to 'antworten', edit_nachrichten_path(nachrichten),  :class => 'btn ', :id => "beantworten"%>
              </td>
            </tr>
          <% end %>
        </tbody>
      </table>
      <%end%>
    </div>
    
  



<br/>
<div class="well sidebar-nav">
  <%nachrichten = Nachrichten.where(sentby: current_user.id)%>
  <% if nachrichten.blank?%>
  <h1>Sie haben bisher keine Nachrichten verschickt</h1>
  <%else%>
    <div class="page-header">
      <h1><%=t '.Gesendete Nachrichten' %></h1>
    </div>
    <table class="table table-striped">
      <thead>
        <tr>
          <th><%= model_class.human_attribute_name(:An )%></th>
          <th><%= model_class.human_attribute_name(:Betreff) %></th>
          <th><%= model_class.human_attribute_name(:Gelesen) %></th>
          <th><%= model_class.human_attribute_name(:Gesendet_am) %></th>
          <th><%= model_class.human_attribute_name(:um) %></th>
          <!--<th><%=t '.actions', :default => t("helpers.actions") %></th>-->
        </tr>
      </thead>
      <tbody>
        <% nachrichten1 = nachrichten.reverse%>
        <% nachrichten1.each do |nachrichten| %>
         <%if nachrichten.sentby == current_user.id%>
          <tr>
            <td><%user1 = User.where(id: nachrichten.sentto).first%><%= user1.firstname %></td>
            <td><%= nachrichten.topic %></td>
            <%if nachrichten.read==false%>
              <td>nein</td>
            <%else%>
              <td>ja</td>
            <%end%>
            <td><%= nachrichten.created_at.day%>.<%=nachrichten.created_at.month%>.<%= nachrichten.created_at.year%></td>
            <td><%= nachrichten.created_at.hour%>:<%= nachrichten.created_at.min%></td>
            <td>
              <%= link_to 'anzeigen', nachrichten, :class => 'btn ', :id => "ansehen"%>
            </td>
          </tr>
         <% end %>
        <%end%>
      </tbody>
    </table>
  <%end%>
</div>

app/views/nachrichtens/new.html.erb
<%- model_class = Nachrichten -%>
<div class="well sidebar-nav">
	<div class="page-header">
  		<h1><%=t '.Neue Nachricht', :model => model_class.model_name.human %></h1>
	</div>
	<%= render :partial => 'form' %>
</div>

app/views/nachrichtens/show.html.erb
<%- model_class = Nachrichten -%>


<div class="container">
    <% flash.each do |name, msg| %>
      <div class="alert alert-<%= name == :notice ? "success" : "error" %>">
      <a class="close" data-dismiss="alert">x</a>
      <%= msg  %>
      </div>
    <% end %>
  </div>

<div class="well sidebar-nav">
<div class="page-header">
  <h1><%=t '.Nachrichten Details' %></h1>
</div>
<%user1 = User.where(id: @nachrichten.sentby).first%>
<%user2= User.where(id: @nachrichten.sentto).first%>

<dl class="dl-horizontal">
  <%if @nachrichten.sentto ==current_user.id%>
  <dt><strong><dt><strong><%= model_class.human_attribute_name(:Sender) %>:</strong></dt>
  <dd><%= user1.firstname %> <%= user1.lastname %> <%if user1.photo_file_name.blank? %>
      <img src="/assets/missing_small.png"   />
      <%else%>
      <%= image_tag freund.photo.url(:tiny)  %>
      <%end%></dd>
  <%else%>
  <dt><strong><%= model_class.human_attribute_name(:Empfänger) %>:</strong></dt>
  <dd><%= user2.firstname  %> <%= user2.lastname  %> <%if user1.photo_file_name.blank? %>
      <img src="/assets/missing_small.png"   />
      <%else%>
      <%= image_tag freund.photo.url(:tiny)  %>
      <%end%></dd>
  <%end%>
  <dt><strong><%= model_class.human_attribute_name(:Betreff) %>:</strong></dt>
  <dd><%= @nachrichten.topic %></dd>
  <dt><strong><%= model_class.human_attribute_name(:Nachricht) %>:</strong></dt>
  <dd><%= @nachrichten.body %></dd>
</dl>

<div class="form-actions">
  <%if user2.id == current_user.id%>
  <%= link_to 'Antworten', edit_nachrichten_path ,:class => 'btn btn-primary', :id =>"beantworten"%>
<%end%>
  <%= link_to t('.Zurück'),nachrichtens_path, :class => 'btn'  %>
 </div>
</div>