config/routes.rb
Paymeback::Application.routes.draw do

  get "users/show"
  resources :nachrichtens
  resources :debits
  resources :friends

 get "startsite/demo" 
  

  ActiveAdmin.routes(self)

  devise_for :users, :path => 'accounts'

  resources :users 
  root to: 'startsite#startsite'

end

app/models/debit.rb
class Debit < ActiveRecord::Base
belongs_to :user

attr_accessible :betrag, :datum, :emailcurrentuser, :emailuser2, :gezahlt, :info, :art, :firstname, :lastname, :read, :owner, :faelligkeit


validates :firstname, presence: true
validates :emailuser2, presence: true
validates_format_of :emailuser2, :with => /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\Z/i, :on => :create, :message => "Ein @ und ein . muss enthalten sein"
validates :betrag, presence: true 

end

app/controllers/debits_controller.rb
class DebitsController < ApplicationController
   load_and_authorize_resource 
   

  # GET /debits
  # GET /debits.json
 
  def index
    debitfriends = current_user.friends.where(accepted: true)
    debitfriends2 = current_user.inverse_friends.where(accepted: true)
    @debitfriendsall = debitfriends + debitfriends2

    if params[:user].present?
      @debits = Debit.where(emailcurrentuser: current_user.email , emailuser2: params[:user], gezahlt: false)    
   else
        if params[:art] == "history"
          @debits = Debit.where(emailcurrentuser: current_user.email)
        else
          @debits = Debit.where(emailcurrentuser: current_user.email, gezahlt: false).group("emailuser2").sum("betrag")    
      end
    end


    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @debits }
    end
  end

  # GET /debits/1
  # GET /debits/1.json
  def show
    @debit = Debit.where(emailcurrentuser: current_user.email , id: params[:id] ).first
  respond_to do |format|
  if @debit == nil
    flash[:error] = "Zugriff Verweigert!  "
    redirect_to debits_path
  else
   if @debit.read == false    
      @debit.read = true
      if @debit.update_attributes(params[:read => true])
        format.html # show.html.erb
        format.json { render json: @debit }
      else
        flash[:error] ="Ein Fehler ist aufgetreten."
        redirect_to root_url
      end
    else
        format.html # show.html.erb
        format.json { render json: @nachrichten }
    end
   end
   end
  end

  # GET /debits/new
  # GET /debits/new.json
  def new
   @debit = Debit.new
   @friends = current_user.friends.where(accepted: true)
   @friends2 = current_user.inverse_friends.where(accepted: true)
  friendsall = @friends + @friends2
   @friend3 = friendsall 
@Fullname = friendsall.map{|friend| {'label' => "#{friend.user.firstname} #{friend.user.lastname}", 'email' => "#{friend.user.email}", 'icon' => "<img src='#{friend.user.photo.url(:tiny)}'/>"}}
   #@Fullname = @friends.map{|friend| {'label' => "#{friend.user.firstname} #{friend.user.lastname}", 'email' => "#{friend.user.email}", 'icon' => "<img src='#{friend.user.photo.url(:tiny)}'/>"}}
   #@Fullname2 = @friends2.map{|friend| {'label' => "#{friend.user.firstname} #{friend.user.lastname}", 'email' => "#{friend.user.email}", 'icon' => "<img src='#{friend.user.photo.url(:tiny)}'/>"}} 
    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @debit }
    end
  end

  # GET /debits/1/edit
  def edit
    @debit = Debit.find(params[:id])
  end

  # POST /debits
  # POST /debits.json
  def create
    @debit = Debit.new(params[:debit])
    @debit.read = true
    if @debit.art == 'Geliehen'
        @art = 'Verliehen'
        @betrag = @debit.betrag
        @debit.betrag=@debit.betrag*-1
    else
      @art= 'Geliehen'
      @betrag = @debit.betrag*-1
    end
    Debit.transaction do
      Debit.create(:emailcurrentuser => @debit.emailuser2, :emailuser2 => @debit.emailcurrentuser, :betrag => @betrag, :art => @art, :info => @debit.info, :datum => @debit.datum, :gezahlt => @debit.gezahlt, :firstname => current_user.firstname+' '+current_user.lastname, :faelligkeit => @debit.faelligkeit)
  end
    respond_to do |format|
      if @debit.save
        format.html { redirect_to debits_path, notice: 'Debit was successfully created.' }
        format.json { render json: @debit, status: :created, location: @debit }
      else
        format.html { render action: "new" }
        format.json { render json: @debit.errors, status: :unprocessable_entity }
      end
    end
   
  end

  # PUT /debits/1
  # PUT /debits/1.json
  def update
    @debit = Debit.find(params[:id])
    @seconddebit = Debit.where(emailcurrentuser: @debit.emailuser2, emailuser2: @debit.emailcurrentuser, datum: @debit.datum, info: @debit.info)
    @seconddebit.each do |debit|
      @helper = Debit.find(debit.id)
    end
    @helper.destroy
    @helper = Debit.new(params[:debit])
    if @helper.art == 'Geliehen'
     
      @helper2 = @helper.betrag*-1
      params[:debit][:betrag] = @helper2
      @helper.art = 'Verliehen'
    else
      @helper.art = 'Geliehen'
      @helper.betrag=@helper.betrag*-1
    end
    Debit.transaction do
      Debit.create(:emailcurrentuser => @helper.emailuser2, :emailuser2 => @helper.emailcurrentuser, :betrag => @helper.betrag, :art => @helper.art, :info => @helper.info, :datum => @helper.datum, :gezahlt => @helper.gezahlt, :firstname => current_user.firstname+' '+current_user.lastname, :faelligkeit => @helper.faelligkeit)
  end      
    respond_to do |format|
      if @debit.update_attributes(params[:debit])
        format.html { redirect_to @debit, notice: 'Eintrag wurde erfolgreich erstellt' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @debit.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /debits/1
  # DELETE /debits/1.json
  def destroy
    @debit = Debit.find(params[:id])
    if @debit.emailcurrentuser == @debit.owner
      @helper = @debit
      @helper.betrag = @helper.betrag*-1
      @seconddebit = Debit.where(emailcurrentuser: @debit.emailuser2, emailuser2: @debit.emailcurrentuser, datum: @debit.datum, info: @debit.info)
      @seconddebit.each do |debit|
        @helper = Debit.find(debit.id)
      end
      @debit.destroy
      @helper.destroy
    else
      flash[:notice] = "Sie haben keine Berechtigung da sie nicht der Besitzer sind."
    end
      respond_to do |format|
        format.html { redirect_to debits_url}
        format.json { head :no_content }
    end
  end
end

app/helpers/debits_helper.rb
module DebitsHelper
end

app/views/debits/_form.html.erb
<%= form_for @debit, :html => { :class => 'form-horizontal' } do |f| %>  
  <% if @debit.errors.any? %>
    <div id="error_explanation">
      <h2>Eintrag konnte nicht erstellt werden! <%= @debit.errors.count %> Fehler wurden gefunden </h2>

      <ul>
      <% @debit.errors.full_messages.each do |msg| %>
      
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>


<link rel="stylesheet" href="http://code.jquery.com/ui/1.10.1/themes/base/jquery-ui.css" />
<script src="http://code.jquery.com/jquery-1.9.1.js"></script>
<script src="http://code.jquery.com/ui/1.10.1/jquery-ui.js"></script>
<script>

      
  $(function() {
 
    $( "#freund" ).autocomplete({
      minLength: 0,
      source: <%= raw "#{@Fullname.to_json}" %>,
     focus: function( event, ui ) {
        $( "#freund" ).val( ui.item.label );
        return false;
      },
      select: function( event, ui ) {
        $( "#email" ).val( ui.item.email );
        
        return false;
      }
    })
    .data( "ui-autocomplete" )._renderItem = function( ul, item ) {
      return $( "<li>" )
        .append( "<a>" + item.label  +" " + item.icon + "</a>" )
        .appendTo( ul );
    };
  }); 
</script>

<!--<%=@Fullname%>
<%=@Fullname2%>-->
      <div class="control-group">
  <%= f.label :Freund, :class => 'control-label' %>
    <div class="controls">
    <%= f.text_field :firstname, :id => "freund", :class => 'text_field' %>
    
    </div>
  </div>
 

    <%= f.hidden_field :emailcurrentuser, :value => current_user.email, :class => 'text_field' %>
    <%= f.hidden_field :owner, :value => current_user.email, :class => 'text_field' %>
 

<br />

  <div class="control-group">
    <%= f.label 'Emailadresse', :class => 'control-label' %>
    <div class="controls">
    <%= f.email_field :emailuser2, :id => "email"%>
  </div>
  </div>

<br />

  <div class="control-group">
    <%= f.label :betrag, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :betrag, :id => 'betrag', :class => 'text_field' %>
    </div>
  </div>

<br />

  <div class="control-group">
    <%= f.label :datum, :class => 'control-label' %>
    <div class="controls">
      <%= f.date_select :datum, :class => 'date_select' %>
    </div>
  </div>

  <div class="control-group">
    <%= f.label 'Fälligkeit', :class => 'control-label' %>
    <div class="controls">
      <%= f.date_select :faelligkeit, :class => 'date_select', :default => {:month => Date.today.next_month.month } %>
    </div>
  </div>

<br />

   <div class="control-group">
 <%= f.label :Info, :class => 'control-label' %>  
 <div class="controls">  
 <%= f.text_field :info, :id => "info" %>
 </div>
  </div>

<br />

  <div class="control-group">
    <%= f.label :art, :class => 'control-label' %>
    <div class="controls">
      <%= f.select :art, [['Verliehen','Verliehen'],['Geliehen','Geliehen']], :id => 'art', :class => 'select' %>
    </div>
  </div>

<br />

  <div class="control-group">
    <%= f.label :gezahlt, :class => 'control-label' %>
    <div class="controls">
      <%= f.check_box :gezahlt, :class => 'text_box' %>
    </div>
  </div>

<br />

  <div class="form-actions">
    <%= f.submit  'Erstellen', :class => 'btn btn-success' %>
 <%= link_to t('.zurück'), debits_path, :class => 'btn'  %>
  </div>
<% end %>

app/views/debits/edit.html.erb
<%- model_class = Debit -%>
<div class="page-header">
  <h1><%=t '.Editieren', :model => model_class.model_name.human %></h1>
</div>
<%= render :partial => 'form' %>

app/views/debits/index.html.erb
<%- model_class = Debit -%>

    <div class="container">
    <% flash.each do |name, msg| %>
      <div class="alert alert-<%= name == :notice ? "success" : "error" %>">
      <a class="close" data-dismiss="alert">x</a>
      <%= msg  %>
      </div>
    <% end %>
  </div>
 

<div class="page-header">
  <h1><%=t '.Zahlungsübersicht' %></h1>
</div>
<div class="well sidebar-nav">
    <% debittest = Debit.where(emailcurrentuser: current_user.email)%>
      <% if debittest.blank?%>
        <h1>Bisher haben Sie kein Geld geliehen oder verliehen </h1>

      <%else%>
    
<p><%= link_to " Aktuelle Übersicht ", "/debits",  :class => ' btn icon-list'%>  <%= link_to " History ", "/debits/?art=history",  :class => 'btn icon-calendar'%></p>

<table class="table table-striped">
  <%if params[:art].present?%>
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:Person) %></th>
      <th><%= model_class.human_attribute_name(:Verliehen) %></th>
      <th><%= model_class.human_attribute_name(:Geliehen) %></th>
      <th><%= model_class.human_attribute_name(:Status) %></th>
      <th><%= model_class.human_attribute_name(:Fälligkeit) %></th>
      <!--<th><%=t '.actions', :default => t("helpers.actions") %></th>-->
    </tr>

  </thead>
  <tbody>
      <% @debits.each do |debit| %>
      <% freund = User.where(email: debit.emailuser2).first%>
      <tr>
      <td><a href='/users/<%=freund.id%>'><%= freund.firstname+' '+freund.lastname %></td>
      <% if debit.art=='Verliehen'%>
            <td><%= link_to sprintf("%.2f",debit.betrag)+' €', debit, {:style=>'color:green;'}%></td>
            <td></td>
            <%if debit.gezahlt == true%>
              <td>Gezahlt!</td>
            <%else%>
              <td>Offen</td>
            <%end%>
            <td><%=debit.faelligkeit.to_formatted_s(:short)%></td>
            <td><%= link_to " Details ", debit,  :class => 'btn icon-info-sign'%>
             <%= link_to t('.Löschen'), debit,:method => :delete,  :data => { :confirm =>  'Are you sure?' }, :class => 'btn btn-danger' %> </td>
            <td></td>
            <% else %>
            <td></td>
            <td><%= link_to sprintf("%.2f",debit.betrag)+' €', debit, {:style=>'color:red;'}%></td>
            <%if debit.gezahlt == true%>
              <td>Gezahlt!</td>
            <%else%>
              <td>Offen</td>
            <%end%>
            <td><%=debit.faelligkeit.to_formatted_s(:short)%></td>
            <td><%= link_to " Details ", debit,  :class => 'btn icon-info-sign'%>
              <%= link_to t('.Löschen'), debit,:method => :delete,  :data => { :confirm =>  'Are you sure?' }, :class => 'btn btn-danger' %> </td>  
        <% end %>
      <% end %>  

<%else%>

<%if params[:user].present? or params[:art].present?%>
 <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:Person) %></th>
      <th><%= model_class.human_attribute_name(:Verliehen) %></th>
      <th><%= model_class.human_attribute_name(:Geliehen) %></th>
      <!--<th><%=t '.actions', :default => t("helpers.actions") %></th>-->
    </tr>

  </thead> 
  <tbody>
      <% @debits.each do |debit| %>
      <% freund = User.where(email: debit.emailuser2).first%>
      <tr>
      <td><a href='/users/<%=freund.id%>'><%= freund.firstname+' '+freund.lastname %></td>
      <% if debit.art=='Verliehen'%>
            <td><%= link_to sprintf("%.2f",debit.betrag)+' €', debit, {:style=>'color:green;'}%></td>
            <td></td>
            <td><%= link_to " Details ", debit,  :class => 'btn icon-info-sign'%>
             <%= link_to t('.Löschen'), debit,:method => :delete,  :data => { :confirm =>  'Are you sure?' }, :class => 'btn btn-danger' %> </td>
            <td></td>
            <% else %>
            <td></td>
            <td><%= link_to sprintf("%.2f",debit.betrag)+' €', debit, {:style=>'color:red;'}%></td>
            <td><%= link_to " Details ", debit,  :class => 'btn icon-info-sign'%>
              <%= link_to t('.Löschen'), debit,:method => :delete,  :data => { :confirm =>  'Are you sure?' }, :class => 'btn btn-danger' %> </td>  
        <% end %>
      <% end %>  

<%else%>
 <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:Person) %></th>
      <th><%= model_class.human_attribute_name(:Verliehen) %></th>
      <th><%= model_class.human_attribute_name(:Geliehen) %></th>
      <!--<th><%=t '.actions', :default => t("helpers.actions") %></th>-->
    </tr>

  </thead> 
  <tbody>
    <% @debits.each do |key, val| %>
    <% freund = User.where(email: key).first%>
    <tr>
      <td><a href='/users/<%=freund.id%>'><%= freund.firstname+' '+freund.lastname %></td>
      <% if val>0%>
            <td><a href='/debits/?user=<%=key%>' style='color: green;' ><%= sprintf("%.2f",val)+' €'%></td>
            <td></td>
            <td><a href='/debits/?user=<%=key%>'  class = 'btn icon-info-sign' > <%=" Detailübersicht "%></td>
            <td></td>
            
            <%else%>
            <td></td>
            <td><a href='/debits/?user=<%=key%>' style='color: red;' ><%= sprintf("%.2f",val)+' €'%></td>
            <td><a href='/debits/?user=<%=key%>'  class = 'btn icon-info-sign' > <%=" Detailübersicht "%></td>

        <%end%>     
   <%end%>
   <%end%>

               
      </tr>
    <% end %>
  </tbody>
</table>
<%end%>
</div>

<div class="well sidebar-nav">
<% if @debitfriendsall.blank?%>
<p><%= link_to t('.Neuer Eintrag', ), nil,:class => 'btn btn-success  disabled' %></p>
   <p>Neuer Eintrag nicht möglich da Sie noch keine Freunde in Ihrer Freundesliste haben!</p>
   <p><%= link_to " Freunde finden", new_friend_path , :class => 'btn btn-success icon-user' %></p>
 <%else%>
<%= link_to t('.Neuer Eintrag', ), new_debit_path,:class => 'btn btn-success' %>
<%end%>
</div>

app/views/debits/new.html.erb
<%- model_class = Debit -%>
<div class="page-header">
  <h1><%=t '.Neuer Eintrag', :model => model_class.model_name.human %></h1>
</div>
<%= render :partial => 'form' %>

app/views/debits/show.html.erb
<%- model_class = Debit -%>
<div class="page-header">
  <h1><%=t '.Eintragsdetails' %></h1>
</div>
<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name("Freund") %>:</strong></dt>
  <dd><%= @debit.firstname %></dd>
  <dt><strong><%= model_class.human_attribute_name("Freund Emailadresse") %>:</strong></dt>
  <dd><%= @debit.emailuser2 %></dd>
  <dt><strong><%= model_class.human_attribute_name(:betrag) %>:</strong></dt>
  <dd><%= sprintf("%.2f",@debit.betrag)+' €' %></dd>
  <dt><strong><%= model_class.human_attribute_name(:datum) %>:</strong></dt>
  <dd><%= @debit.datum %></dd>
  <dt><strong><%= model_class.human_attribute_name("Fälligkeit") %>:</strong></dt>
  <dd><%= @debit.faelligkeit %></dd>
  <dt><strong><%= model_class.human_attribute_name(:art) %>:</strong></dt>
  <dd><%= @debit.art %></dd>
  <dt><strong><%= model_class.human_attribute_name(:gezahlt) %>:</strong></dt>
  <dd><%= @debit.gezahlt %></dd>
  <dt><strong><%= model_class.human_attribute_name(:info) %>:</strong></dt>
  <dd> <%= @debit.info %></dd>
</dl>

<div class="form-actions">
<%user =User.where(email: @debit.emailuser2).first%>
  
  <%= link_to t('.bearbeiten'), edit_debit_path(@debit), :class => 'btn btn-success' %>
  <%= link_to t('.Löschen'), @debit,:method => :delete,  :data => { :confirm =>  'Are you sure?' }, :class => 'btn btn-danger' %> 
  <%= link_to t('.Frage senden'), new_nachrichten_path(:sentto => user.id , :topic => @debit.info), :method => :get, :class =>'btn icon-envelope'%>
  <%= link_to t('.Zurück'), debits_path, :class => 'btn'  %>
</div>