config/routes.rb
Paymeback::Application.routes.draw do

  get "users/show"
  resources :nachrichtens
  resources :debits
  resources :friends

 get "startsite/demo" 
  

  ActiveAdmin.routes(self)

  devise_for :users, :path => 'accounts'

  resources :users 
  root to: 'startsite#startsite'

end

app/helpers/layout_helper.rb
# These helper methods can be called in your template to set variables to be used in the layout
# This module should be included in all views globally,
# to do so you may need to add this line to your ApplicationController
#   helper :layout
module LayoutHelper
  def title(page_title, show_title = true)
    content_for(:title) { h(page_title.to_s) }
    @show_title = show_title
  end

  def show_title?
    @show_title
  end

  def stylesheet(*args)
    content_for(:head) { stylesheet_link_tag(*args) }
  end

  def javascript(*args)
    content_for(:head) { javascript_include_tag(*args) }
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Paymeback" %></title>
    <meta name="description" content="">
    <meta name="author" content="">
      
    <!-- Le styles -->
    <link href="../assets/css/bootstrap.css" rel="stylesheet">
    <style type="text/css">
      body {
        padding-top: 20px;
        padding-bottom: 60px;
        margin: 0 auto;
      }

      /* Custom container */
      .container {
        margin: 0 auto;
        max-width: 1600px;
      }
      .container > hr {
       margin: 40px 0;
      }

      /* Main marketing message and sign up button */
     .jumbotron {
       margin: 5px auto;
       text-align: center;
     }
     .jumbotron h1 {
       font-size: 100px;
       line-height: 1;
     }
      .jumbotron .lead {
       font-size: 24px;
       line-height: 1.25;
     }
     .jumbotron .btn {
       font-size: 21px;
       padding: 14px 24px;
     }  

      /* Supporting marketing content */
     .marketing {
       margin: 60px 0;
     }
     .marketing p + h4 {
       margin-top: 28px;
     }
  </style>
    <%= csrf_meta_tags %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js" type="text/javascript"></script>
    <![endif]-->

    <%= stylesheet_link_tag "application", :media => "all" %>


  <body>


    <div class="navbar navbar-fluid-top">
      <div class="navbar-inner">
        <div class="container-fluid">


          <a class="brand" href="/">Paymeback</a>
          

            <% if current_user %>
              <ul class="nav">
                <li><a href="/">Home</a></li>
                <li class="dropdown">
                  <a data-toggle="dropdown" class="dropdown-toggle" href="#">Profil<b class="caret"></b></a>
                     <ul class="dropdown-menu">
                      <li><a href="/users/<%= current_user.id%>">Mein Profil</a></li>
                      <li><%= link_to 'Freunde', friends_path%></li>
                      <li><%= link_to "Freunde finden", new_friend_path %></li>
                    </ul>
                  </li>
                  <li class="dropdown">
                  <a data-toggle="dropdown" class="dropdown-toggle" href="#">Zahlungsübersicht<b class="caret"></b></a>
                     <ul class="dropdown-menu">
                      <li><%= link_to 'Übersicht', debits_path%></li>
                      <li><%= link_to "Neue Schulden eintragen", new_debit_path %></li>
                    </ul>
                  </li>
                  <% typ = Friend.where(friend_id: current_user.id)%>
                <% @count=0 %>
                <%typ.all.each do |type|%>
                  <%if type.accepted == false%> 
                    <% @count+=1 %>
                  <%end%>
                <%end%>
                <%messages = Nachrichten.where(sentto: current_user.id , read: false)%>
                <%messages.all.each do |message|%>
                  <% @count+=1 %>
                <%end%>
                <%debitnum = Debit.where(emailcurrentuser: current_user.email, read: false)%>
                <%debitnum.all.each do |debit|%>
                <% @count+=1%>
                <% end %>
                <!--<%debitablauf = Debit.where("emailcurrentuser like ? and faelligkeit < ?", current_user.email, DateTime.now) %>-->
                <%debitablauf = Debit.where(emailcurrentuser: current_user.email, gezahlt: false) %>
                <%debitablauf.all.each do |debit|%>
                <%if debit.faelligkeit < DateTime.now%>
                  <% @count+=1%>
                <%end%>
                <% end %>           
                <% if @count>0 %>
                  <% if @count == 1%>
                    <% @Nachricht=' Benachrichtigung'%>
                    <% else %>
                    <% @Nachricht=' Benachrichtigungen'%>
                    <%end%>
                  <li class="dropdown active">
                  <a data-toggle="dropdown" class="dropdown-toggle" href="#"><b><%= @count.to_s+' '+@Nachricht %></b></a>
                    <ul class="dropdown-menu">
                      <%typ.all.each do |type|%>
                        <%if type.accepted == false%> 
                          <% user = User.where(id: type.user_id).first%>
                          <li>
                            <a href="/users/<%=user.id%>">Freundschaftsanfrage: <%=user.firstname%> <%=user.lastname%><i class="icon-arrow-right"></i>
                            <ul class="dropdown-menu sub-menu">
                              <li><%= link_to "annehmen", type, :method => :put %></li>     
                              <li><%= link_to "ablehnen", type, :method => :delete %></li>
                            </ul>
                          </li>
                           <%end%>
                           <%end%>
                           <%messages.all.each do |message|%>
                           <%freund = User.find(message.sentby)%>
                           <li>
                            <%= link_to 'Nachricht von: '+freund.firstname+' '+freund.lastname , nachrichten_path(:id => message)%>
                            </li>
                            <%end%>
                            <%debitnum.all.each do |debit|%>
                           <%freund = User.where(email: debit.emailuser2).first%>
                           <li>
                            <%= link_to 'Neue Schulden: '+freund.firstname+' '+freund.lastname , debit_path(:id => debit)%>
                            </li>
                            <%end%>
                            <%debitablauf.all.each do |debit|%>
                            <%if debit.faelligkeit < DateTime.now%>
                              <%freund = User.where(email: debit.emailuser2).first%>
                              <li>
                              <%= link_to 'Fälligkeitsdatum überschritten: '+freund.firstname+' '+freund.lastname , debit_path(:id => debit)%>
                              </li>
                            <%end%>
                          <%end%>

                      </ul>
                      <%end%>      
              </ul>
              <ul class="nav pull-right" >
              <p></p>
                <p><%= link_to current_user.firstname+' '+current_user.lastname, destroy_user_session_path,:class => "  icon-off  ", method: :delete  %> </p>
                
            </ul>
              <%else%>
               <ul class="nav">
              <li><%= link_to 'Anmelden', new_user_session_path  %></li>
              <li><%= link_to 'Registrieren', new_user_registration_path  %></li>
              </ul>
              <ul style = "float: right" class="nav pull-right">
              <li><%= link_to 'Demo', "/startsite/demo" %></li>
              
              </ul>
              <%end%>
            
            
          <!--/.nav-collapse -->
        </div>
      </div>
    </div>
  <%if current_user%>
    <div class="container-fluid">
      <div class="row-fluid">
        <div class="span2">
          <div class="well sidebar-nav">
            <ul class="nav nav-list">
              <!--<li class="nav-header">Sidebar</li>-->
              <% if current_user %>

              <li><%= link_to 'Zahlungsübersicht', debits_path, :id=> 'Zahlungen'%></li>
              <li><%= link_to 'Freunde', friends_path, :id => "freundebutton"%></li>

              <li><%= link_to 'Nachrichten', nachrichtens_path%></li>
              <% if current_user.email == "admin@admin.de"%>  
              <li><%= link_to 'Benutzerverwaltung', "/admin/users" %></li>
              <%end%>
              <li><%= link_to 'Einstellungen', edit_user_registration_path %></li>
              <li><%= link_to 'Home', root_path, method: :delete %></li>
              <%end%>
            </ul>
          </div><!--/.well -->
        </div><!--/span-->
        <div class="span9">
            <%= yield %>
        </div>
      </div>
    </div>
  
  <%else%>
    <div class="container">
    <% flash.each do |name, msg| %>
      <div class="alert alert-<%= name == :notice ? "success" : "error" %>">
      <a class="close" data-dismiss="alert">x</a>
      <%= msg  %>
      </div>
    <% end %>
  <%= yield %>
  </div>
  <%end%>

    <!-- Javascripts
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <%= javascript_include_tag "application" %>

  </body>
</html>
 